using System.Text;
using Eryph.GuestServices.Core;
using Eryph.GuestServices.Sockets;

namespace Eryph.GuestServices.Tool;

public static class SshConfigHelper
{
    private const string Border = "# ------ eryph guest services ------";

    // Suffixes reserved for the auto-generated canonical hosts:
    // "<vmId>.hyper-v.alt" for VMs and "<...>.eryph.alt" for catlets. A
    // user-supplied alias must not use them: a "*.hyper-v.alt" alias could
    // shadow another VM's canonical token, and a "*.eryph.alt" alias collides
    // with catlet hosts that update-ssh-config regenerates (and catlet.d is
    // Included before vm.d, so the catlet would even shadow the VM). Rejecting
    // these keeps every user alias outside the generated namespaces.
    private static readonly string[] ReservedAliasSuffixes = [".hyper-v.alt", ".eryph.alt"];

    public static bool IsReservedAlias(string alias) =>
        ReservedAliasSuffixes.Any(suffix => alias.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));

    // Test seam: overrides the config root so the writers and the alias-dedup
    // sweep can be exercised against a temp directory instead of the real user
    // profile. Null in production.
    internal static string? RootPathOverride { get; set; }

    // The config should be in the local (non-roaming) profile as the connection
    // only works on the specific machine.
    private static string EryphSshConfigPath => RootPathOverride ?? Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        ".eryph",
        "guest-services",
        "ssh");

    public static string CatletSshConfigPath => Path.Combine(EryphSshConfigPath, "catlet.d");

    public static string VmSshConfigPath => Path.Combine(EryphSshConfigPath, "vm.d");

    public static async Task EnsureSshConfigAsync()
    {
        var sshUserProfilePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".ssh");

        var sshConfigPath = Path.Combine(sshUserProfilePath, "config");

        var config = $"""
                       {Border}
                       # This part of the configuration has been auto-generated by
                       # the eryph guest services and should not be modified manually.
                       
                       Include {CatletSshConfigPath}\*
                       Include {VmSshConfigPath}\*
                       
                       {Border}
                       """;

        if (!File.Exists(sshConfigPath))
        {
            Directory.CreateDirectory(sshUserProfilePath);
            await File.WriteAllTextAsync(sshConfigPath, config);
            return;
        }

        var sshConfig = await File.ReadAllTextAsync(sshConfigPath);
        if (string.IsNullOrWhiteSpace(sshConfig))
        {
            await File.WriteAllTextAsync(sshConfigPath, config);
            return;
        }
        
        var configStart = sshConfig.IndexOf(Border, StringComparison.Ordinal);
        if (configStart < 0)
        {
            await File.WriteAllTextAsync(sshConfigPath, $"{config}{Environment.NewLine}{sshConfig}");
            return;
        }

        var configEnd = sshConfig.IndexOf(Border, configStart + Border.Length, StringComparison.Ordinal);
        if (configEnd < 0)
            throw new InvalidOperationException(
                "The SSH config contains a broken eryph guest services configuration. "
                + $"Please cleanup your SSH config with can be found at '{sshConfigPath}'.");

        await File.WriteAllTextAsync(
            sshConfigPath,
            sshConfig[..configStart] + config + sshConfig[(configEnd + Border.Length)..]);
    }

    public static async Task<IReadOnlyList<string>> EnsureCatletConfigAsync(
        string catletId,
        string catletName,
        string projectName,
        Guid vmId,
        string keyFilePath)
    {
        IReadOnlyList<string> aliases = [$"{catletId}.eryph.alt", $"{catletName}.{projectName}.eryph.alt"];
        if (projectName == "default")
            aliases = [..aliases, $"{catletName}.eryph.alt"];

        Directory.CreateDirectory(CatletSshConfigPath);
        await WriteConfig(
            Path.Combine(CatletSshConfigPath, $"{catletId}.config"),
            aliases,
            vmId,
            keyFilePath);

        return aliases;
    }

    public static async Task<IReadOnlyList<string>> EnsureVmConfigAsync(
        Guid vmId,
        string? alias,
        string keyFilePath)
    {
        IReadOnlyList<string> aliases = [$"{vmId}.hyper-v.alt"];
        if (!string.IsNullOrEmpty(alias))
           aliases = [alias, ..aliases];

        Directory.CreateDirectory(VmSshConfigPath);
        var ownConfigPath = Path.Combine(VmSshConfigPath, $"{vmId}.config");

        // An SSH alias must resolve to exactly one host. The user-supplied alias
        // is not constrained to a single VM, so re-using it for another VM (or
        // an alias that already names a catlet) would leave two 'Host <alias>'
        // stanzas across the included config files. OpenSSH processes the
        // Include glob in lexical order and the first match wins, so the alias
        // could silently resolve to a different (often stale/stopped) VM and the
        // ProxyCommand would connect to the wrong vmId. Evict the alias from any
        // other config so the VM we are configuring now owns it.
        //
        // Only the user-supplied alias is swept: the per-VM "<vmId>.hyper-v.alt"
        // token is unique by construction and can never legitimately collide, so
        // it must not be fed to the sweep (doing so could strip another VM's
        // canonical token from its config).
        if (!string.IsNullOrEmpty(alias))
            await RemoveAliasesFromOtherConfigsAsync([alias], ownConfigPath);

        await WriteConfig(
            ownConfigPath,
            aliases,
            vmId,
            keyFilePath);

        return aliases;
    }

    // Removes the given <paramref name="aliases"/> from every auto-generated VM
    // and catlet config file except <paramref name="ownConfigPath"/>. A file
    // that still has at least one alias left is rewritten. A file whose Host
    // line would be emptied is left untouched: that only happens when the alias
    // is that config's sole identity (e.g. a VM's "&lt;vmId&gt;.hyper-v.alt"
    // token typed verbatim as another VM's alias), and silently deleting it
    // would orphan an existing host. Keeping it preserves reachability.
    private static async Task RemoveAliasesFromOtherConfigsAsync(
        IReadOnlyList<string> aliases,
        string ownConfigPath)
    {
        var aliasesToRemove = new HashSet<string>(aliases, StringComparer.Ordinal);
        var ownFullPath = Path.GetFullPath(ownConfigPath);

        foreach (var directory in new[] { VmSshConfigPath, CatletSshConfigPath })
        {
            if (!Directory.Exists(directory))
                continue;

            foreach (var file in Directory.EnumerateFiles(directory, "*.config", SearchOption.TopDirectoryOnly))
            {
                if (string.Equals(Path.GetFullPath(file), ownFullPath, StringComparison.OrdinalIgnoreCase))
                    continue;

                await RemoveAliasesFromConfigFileAsync(file, aliasesToRemove);
            }
        }
    }

    private static async Task RemoveAliasesFromConfigFileAsync(
        string file,
        HashSet<string> aliasesToRemove)
    {
        string[] lines;
        try
        {
            lines = await File.ReadAllLinesAsync(file);
        }
        catch
        {
            // A config we cannot read cannot be safely rewritten. Leaving it in
            // place is no worse than the pre-existing state.
            return;
        }

        var hostLineIndex = Array.FindIndex(
            lines,
            line => line.TrimStart().StartsWith("Host ", StringComparison.Ordinal));
        if (hostLineIndex < 0)
            return;

        var tokens = lines[hostLineIndex].Split(' ', StringSplitOptions.RemoveEmptyEntries);
        // tokens[0] is the "Host" keyword; the remainder are the aliases.
        var keptAliases = tokens.Skip(1).Where(t => !aliasesToRemove.Contains(t)).ToList();
        if (keptAliases.Count == tokens.Length - 1)
            return;

        if (keptAliases.Count == 0)
            // The alias is this config's only identity; stripping it would leave
            // a dangling, unreachable host. Leave the file as-is.
            return;

        lines[hostLineIndex] = "Host " + string.Join(' ', keptAliases);
        try
        {
            await File.WriteAllLinesAsync(file, lines);
        }
        catch
        {
            // Ignore: failing to drop the alias here only means the duplicate
            // persists, which is the pre-existing behaviour we are improving.
        }
    }

    private static async Task WriteConfig(
        string path,
        IReadOnlyList<string> aliases,
        Guid vmId,
        string keyFilePath)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# This file was auto-generated by the eryph guest services and");
        builder.AppendLine("# should not be edited manually.");
        builder.AppendLine($"Host {string.Join(' ', aliases)}");
        builder.AppendLine($"    HostName {vmId}.hyper-v.alt");
        builder.AppendLine($"    User egs");
        builder.AppendLine($"    IdentityFile {keyFilePath}");
        // Explicitly disable other authentication methods. This prevents
        // the SSH client from prompting for authentication when the private
        // key is not available. Other authentication methods would not work
        // anyway as the eryph guest services only support public key authentication.
        builder.AppendLine($"    KbdInteractiveAuthentication no");
        builder.AppendLine($"    PasswordAuthentication no");
        // Disable host key checking. The connection can only be established via
        // a local Hyper-V socket which is only accessible by administrators.
        builder.AppendLine($"    StrictHostKeyChecking no");
        // Prefer the GCM ciphers as they are significantly faster in
        // Microsoft.DevTunnels.SSH. In OpenSSH 9.9, this is the default
        // anyway. Unfortunately, Windows still ships an older version which
        // prefers the CTR ciphers.
        builder.AppendLine($"    Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr");
        // We use our own proxy command instead of hvc nc. This enables support
        // for older versions of Hyper-V as hvc nc is only available in Windows
        // 1809 or newer.
        builder.AppendLine($"    ProxyCommand egs-tool.exe proxy {vmId}");
        // builder.AppendLine($"    ProxyCommand hvc nc -t vsock {vmId} {hvPort}");
        builder.AppendLine("");
        
        await File.WriteAllTextAsync(path, builder.ToString());
    }

    public static Task CleanupCatletConfigsAsync(IList<string> catletIds) => Task.Run(() =>
    {
        if (!Directory.Exists(CatletSshConfigPath))
            return;

        var files = Directory.EnumerateFiles(CatletSshConfigPath, "*.config", SearchOption.TopDirectoryOnly);
        foreach (var file in files)
        {
            var fileName = Path.GetFileNameWithoutExtension(file);
            if (catletIds.Contains(fileName))
                continue;

            try
            {
                File.Delete(file);
            }
            catch
            {
                // Ignore error when deleting the file. We just keep an unused config file
                // which should not cause any issues.
            }
        }
    });
}

