using System.Text;
using Eryph.GuestServices.Core;
using Eryph.GuestServices.Sockets;

namespace Eryph.GuestServices.Tool;

public static class SshConfigHelper
{
    private const string Border = "# ------ eryph guest services ------";

    // Suffixes reserved for eryph-managed hosts. ".hyper-v.alt" is the canonical
    // per-VM host generated by add-ssh-config; ".eryph.alt" is reserved for the
    // (future) eryph catlet integration. A user-supplied alias must not use
    // either: a "*.hyper-v.alt" alias could shadow another VM's canonical token,
    // and reserving ".eryph.alt" keeps user aliases out of the eryph namespace
    // so the later integration cannot collide with them.
    private static readonly string[] ReservedAliasSuffixes = [".hyper-v.alt", ".eryph.alt"];

    public static bool IsReservedAlias(string alias) =>
        ReservedAliasSuffixes.Any(suffix => alias.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));

    // Validates a user-supplied alias before it is written into a 'Host' line.
    // Returns a human-readable error, or null when the alias is acceptable.
    public static string? GetAliasValidationError(string alias)
    {
        // Restrict to a safe host-token charset. Anything outside it could change
        // how the generated 'Host' line is parsed: whitespace splits it into
        // multiple patterns, a newline injects arbitrary directives, and
        // ssh_config metacharacters such as '#' (comment), '!' (negation) and
        // '*'/'?' (patterns) alter its meaning. Do not echo the alias in this
        // message: a control character (e.g. ESC) in it could inject terminal
        // escape sequences when printed.
        if (!alias.All(IsAllowedAliasChar))
            return "The alias may only contain ASCII letters, digits, '.', '-' and '_'.";

        if (IsReservedAlias(alias))
            return $"The alias '{alias}' uses a reserved suffix (.hyper-v.alt or .eryph.alt) "
                + "that is managed by the eryph guest services.";

        return null;
    }

    private static bool IsAllowedAliasChar(char c) =>
        char.IsAsciiLetterOrDigit(c) || c is '.' or '-' or '_';

    // Test seam: overrides the config root so the writers and the alias-dedup
    // sweep can be exercised against a temp directory instead of the real user
    // profile. Null in production.
    internal static string? RootPathOverride { get; set; }

    // The config should be in the local (non-roaming) profile as the connection
    // only works on the specific machine.
    private static string EryphSshConfigPath => RootPathOverride ?? Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        ".eryph",
        "guest-services",
        "ssh");

    public static string VmSshConfigPath => Path.Combine(EryphSshConfigPath, "vm.d");

    // Per-catlet eryph-channel configs live in their own include directory so
    // they coexist with the VM-level (.hyper-v.alt) configs without either
    // sweep touching the other's files.
    public static string CatletSshConfigPath => Path.Combine(EryphSshConfigPath, "catlet.d");

    public static async Task EnsureSshConfigAsync()
    {
        var sshUserProfilePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".ssh");

        var sshConfigPath = Path.Combine(sshUserProfilePath, "config");

        var config = $"""
                       {Border}
                       # This part of the configuration has been auto-generated by
                       # the eryph guest services and should not be modified manually.

                       Include {CatletSshConfigPath}\*
                       Include {VmSshConfigPath}\*

                       {Border}
                       """;

        if (!File.Exists(sshConfigPath))
        {
            Directory.CreateDirectory(sshUserProfilePath);
            await File.WriteAllTextAsync(sshConfigPath, config);
            return;
        }

        var sshConfig = await File.ReadAllTextAsync(sshConfigPath);
        if (string.IsNullOrWhiteSpace(sshConfig))
        {
            await File.WriteAllTextAsync(sshConfigPath, config);
            return;
        }
        
        var configStart = sshConfig.IndexOf(Border, StringComparison.Ordinal);
        if (configStart < 0)
        {
            await File.WriteAllTextAsync(sshConfigPath, $"{config}{Environment.NewLine}{sshConfig}");
            return;
        }

        var configEnd = sshConfig.IndexOf(Border, configStart + Border.Length, StringComparison.Ordinal);
        if (configEnd < 0)
            throw new InvalidOperationException(
                "The SSH config contains a broken eryph guest services configuration. "
                + $"Please cleanup your SSH config with can be found at '{sshConfigPath}'.");

        await File.WriteAllTextAsync(
            sshConfigPath,
            sshConfig[..configStart] + config + sshConfig[(configEnd + Border.Length)..]);
    }

    public static async Task<IReadOnlyList<string>> EnsureVmConfigAsync(
        Guid vmId,
        string? alias,
        string keyFilePath)
    {
        IReadOnlyList<string> aliases = [$"{vmId}.hyper-v.alt"];
        if (!string.IsNullOrEmpty(alias))
           aliases = [alias, ..aliases];

        Directory.CreateDirectory(VmSshConfigPath);
        var ownConfigPath = Path.Combine(VmSshConfigPath, $"{vmId}.config");

        // Write our own config before sweeping the others. If WriteConfig fails,
        // having already stripped the alias from its previous owner would lose
        // it entirely; doing this first means a later sweep failure only leaves
        // the pre-existing duplicate behind.
        await WriteConfig(
            ownConfigPath,
            aliases,
            vmId,
            keyFilePath);

        // An SSH alias must resolve to exactly one host. The user-supplied alias
        // is not constrained to a single VM, so re-using it for another VM (or
        // an alias that already names a catlet) would leave two 'Host <alias>'
        // stanzas across the included config files. OpenSSH processes the
        // Include glob in lexical order and the first match wins, so the alias
        // could silently resolve to a different (often stale/stopped) VM and the
        // ProxyCommand would connect to the wrong vmId. Evict the alias from any
        // other config so the VM we are configuring now owns it.
        //
        // Only the user-supplied alias is swept: the per-VM "<vmId>.hyper-v.alt"
        // token is unique by construction and can never legitimately collide, so
        // it must not be fed to the sweep (doing so could strip another VM's
        // canonical token from its config).
        if (!string.IsNullOrEmpty(alias))
            await RemoveAliasesFromOtherConfigsAsync([alias], ownConfigPath);

        return aliases;
    }

    // Builds the SSH host aliases for a single catlet reached over the eryph
    // channel. The canonical, always-unique alias is "<catletId>.eryph.alt"; a
    // friendly "<name>.<project>.eryph.alt" is added, and for the default
    // project the shorter "<name>.eryph.alt" too. Kept pure (no IO) so the alias
    // shape can be unit-tested directly.
    public static IReadOnlyList<string> GetCatletAliases(
        string catletId,
        string catletName,
        string projectName)
    {
        IReadOnlyList<string> aliases =
            [$"{catletId}.eryph.alt", $"{catletName}.{projectName}.eryph.alt"];
        if (string.Equals(projectName, "default", StringComparison.Ordinal))
            aliases = [..aliases, $"{catletName}.eryph.alt"];

        return aliases;
    }

    // Writes a single per-catlet SSH config whose ProxyCommand bridges to the
    // eryph channel (egs-tool eryph proxy <catletId>) rather than a local
    // hvsocket. Per-catlet and on demand: unlike the removed bulk
    // update-ssh-config it never enumerates or rewrites other catlets' configs.
    public static async Task<IReadOnlyList<string>> EnsureCatletConfigAsync(
        string catletId,
        string catletName,
        string projectName,
        string keyFilePath)
    {
        var aliases = GetCatletAliases(catletId, catletName, projectName);

        Directory.CreateDirectory(CatletSshConfigPath);
        await WriteCatletConfig(
            Path.Combine(CatletSshConfigPath, $"{catletId}.config"),
            aliases,
            catletId,
            keyFilePath);

        return aliases;
    }

    // Removes the given <paramref name="aliases"/> from every auto-generated VM
    // config file except <paramref name="ownConfigPath"/>. A file that still has
    // at least one alias left is rewritten. A file whose Host line would be
    // emptied is left untouched: that only happens when the alias is that
    // config's sole identity (e.g. a VM's "&lt;vmId&gt;.hyper-v.alt" token typed
    // verbatim as another VM's alias), and silently deleting it would orphan an
    // existing host. Keeping it preserves reachability.
    private static async Task RemoveAliasesFromOtherConfigsAsync(
        IReadOnlyList<string> aliases,
        string ownConfigPath)
    {
        // Match case-insensitively: SSH host aliases are effectively
        // case-insensitive, so 'web' and 'WEB' must be treated as the same
        // alias or the sweep would leave a casing-only duplicate behind.
        var aliasesToRemove = new HashSet<string>(aliases, StringComparer.OrdinalIgnoreCase);
        var ownFullPath = Path.GetFullPath(ownConfigPath);

        string[] files;
        try
        {
            if (!Directory.Exists(VmSshConfigPath))
                return;

            files = Directory.GetFiles(VmSshConfigPath, "*.config", SearchOption.TopDirectoryOnly);
        }
        catch
        {
            // Best-effort: a directory we cannot enumerate (permissions, or
            // removed between the check and the call) just skips de-duplication;
            // it must never fail the command.
            return;
        }

        foreach (var file in files)
        {
            if (string.Equals(Path.GetFullPath(file), ownFullPath, StringComparison.OrdinalIgnoreCase))
                continue;

            await RemoveAliasesFromConfigFileAsync(file, aliasesToRemove);
        }
    }

    private static async Task RemoveAliasesFromConfigFileAsync(
        string file,
        HashSet<string> aliasesToRemove)
    {
        string[] lines;
        try
        {
            lines = await File.ReadAllLinesAsync(file);
        }
        catch
        {
            // A config we cannot read cannot be safely rewritten. Leaving it in
            // place is no worse than the pre-existing state.
            return;
        }

        var hostLineIndex = Array.FindIndex(lines, IsHostLine);
        if (hostLineIndex < 0)
            return;

        // Split on any whitespace (space or tab, both valid ssh-config
        // separators) so the sweep is robust to hand-edited files.
        var tokens = lines[hostLineIndex].Split(
            (char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        // tokens[0] is the "Host" keyword; the remainder are the aliases.
        var keptAliases = tokens.Skip(1).Where(t => !aliasesToRemove.Contains(t)).ToList();
        if (keptAliases.Count == tokens.Length - 1)
            return;

        if (keptAliases.Count == 0)
            // The alias is this config's only identity; stripping it would leave
            // a dangling, unreachable host. Leave the file as-is.
            return;

        lines[hostLineIndex] = "Host " + string.Join(' ', keptAliases);
        try
        {
            await File.WriteAllLinesAsync(file, lines);
        }
        catch
        {
            // Ignore: failing to drop the alias here only means the duplicate
            // persists, which is the pre-existing behaviour we are improving.
        }
    }

    // A 'Host' stanza: the keyword (case-insensitive, per ssh_config) followed
    // by any whitespace (space or tab). Matching only "Host " would miss a
    // tab-separated line in a hand-edited config.
    private static bool IsHostLine(string line)
    {
        var trimmed = line.TrimStart();
        return trimmed.Length > 4
            && trimmed.StartsWith("Host", StringComparison.OrdinalIgnoreCase)
            && char.IsWhiteSpace(trimmed[4]);
    }

    private static async Task WriteConfig(
        string path,
        IReadOnlyList<string> aliases,
        Guid vmId,
        string keyFilePath)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# This file was auto-generated by the eryph guest services and");
        builder.AppendLine("# should not be edited manually.");
        builder.AppendLine($"Host {string.Join(' ', aliases)}");
        builder.AppendLine($"    HostName {vmId}.hyper-v.alt");
        builder.AppendLine($"    User egs");
        builder.AppendLine($"    IdentityFile {keyFilePath}");
        // Explicitly disable other authentication methods. This prevents
        // the SSH client from prompting for authentication when the private
        // key is not available. Other authentication methods would not work
        // anyway as the eryph guest services only support public key authentication.
        builder.AppendLine($"    KbdInteractiveAuthentication no");
        builder.AppendLine($"    PasswordAuthentication no");
        // Disable host key checking. The connection can only be established via
        // a local Hyper-V socket which is only accessible by administrators.
        builder.AppendLine($"    StrictHostKeyChecking no");
        // Prefer the GCM ciphers as they are significantly faster in
        // Microsoft.DevTunnels.SSH. In OpenSSH 9.9, this is the default
        // anyway. Unfortunately, Windows still ships an older version which
        // prefers the CTR ciphers.
        builder.AppendLine($"    Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr");
        // We use our own proxy command instead of hvc nc. This enables support
        // for older versions of Hyper-V as hvc nc is only available in Windows
        // 1809 or newer.
        builder.AppendLine($"    ProxyCommand egs-tool.exe proxy {vmId}");
        // builder.AppendLine($"    ProxyCommand hvc nc -t vsock {vmId} {hvPort}");
        builder.AppendLine("");
        
        await File.WriteAllTextAsync(path, builder.ToString());
    }

    private static async Task WriteCatletConfig(
        string path,
        IReadOnlyList<string> aliases,
        string catletId,
        string keyFilePath)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# This file was auto-generated by the eryph guest services and");
        builder.AppendLine("# should not be edited manually.");
        builder.AppendLine($"Host {string.Join(' ', aliases)}");
        // HostName is irrelevant: the ProxyCommand supplies the transport (the
        // eryph channel), not a TCP/hvsocket address. Keep a stable token so
        // OpenSSH has a non-empty hostname to substitute.
        builder.AppendLine($"    HostName {catletId}.eryph.alt");
        builder.AppendLine($"    User egs");
        builder.AppendLine($"    IdentityFile {keyFilePath}");
        // Disable interactive/password auth: the eryph channel only carries
        // public-key SSH, so prompting would only ever fail.
        builder.AppendLine($"    KbdInteractiveAuthentication no");
        builder.AppendLine($"    PasswordAuthentication no");
        // The guest is reached through eryph's authorized channel; the guest's
        // host key is not pre-known to the operator, so do not block on it.
        builder.AppendLine($"    StrictHostKeyChecking no");
        // Prefer the GCM ciphers as they are significantly faster in
        // Microsoft.DevTunnels.SSH (the guest's SSH server).
        builder.AppendLine($"    Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr");
        // The data plane: SSH pipes its traffic through the eryph channel.
        builder.AppendLine($"    ProxyCommand egs-tool.exe eryph proxy {catletId}");
        builder.AppendLine("");

        await File.WriteAllTextAsync(path, builder.ToString());
    }
}

