using System.Net.WebSockets;
using Eryph.GuestServices.Tool.Eryph;
using Microsoft.DevTunnels.Ssh;
using Microsoft.DevTunnels.Ssh.Algorithms;
using Microsoft.DevTunnels.Ssh.Keys;

namespace Eryph.GuestServices.Tool.Transport;

// Reaches the guest over the eryph remote channel: opens the data-plane WebSocket
// (EryphChannel) and runs the SSH session over it in-process via WebSocketStream.
//
// Authenticates with the operator's managed client key, or a BYOK key when an
// identity path is given — the same keys the generated 'catlet add-ssh-config'
// alias would present. The guest must already authorize that public key, either
// pre-injected at build time or pushed with 'catlet add-key'.
internal sealed class EryphGuestConnector(
    string catletId,
    string? clientId,
    string? configurationName,
    string? identityPath,
    Action<string>? writeWarning) : IGuestConnector
{
    public async Task<GuestSshConnection> ConnectAsync(CancellationToken cancellation)
    {
        var connection = EryphConnection.Resolve(clientId, configurationName)
            ?? throw new GuestConnectionException(
                "Could not find an eryph connection. Is eryph configured or eryph-zero running?");

        var keyPair = await ResolveKeyAsync();

        var webSocket = await EryphChannel.OpenAsync(connection, catletId, writeWarning, cancellation);

        // Run SSH directly over the channel in-process. The .NET 10 WebSocketStream
        // wraps the socket as a byte stream (binary frames, 0-byte read on close)
        // and owns it, so disposing the stream closes the socket. Until the stream
        // exists the socket is disposed directly on failure so it never leaks.
        Stream stream;
        try
        {
            stream = WebSocketStream.Create(webSocket, WebSocketMessageType.Binary, ownsWebSocket: true);
        }
        catch
        {
            webSocket.Dispose();
            throw;
        }

        try
        {
            var session = await GuestSsh.EstablishSessionAsync(stream, keyPair);
            return new GuestSshConnection(session, stream);
        }
        catch
        {
            await stream.DisposeAsync();
            throw;
        }
    }

    // The managed key (created on demand under the operator's profile) by default,
    // or the BYOK private key the operator selected with --identity. The BYOK key
    // is loaded here because the in-process session has to sign with it, unlike
    // 'catlet add-ssh-config' which only writes its path into the ssh_config.
    private async Task<IKeyPair> ResolveKeyAsync()
    {
        if (string.IsNullOrEmpty(identityPath))
        {
            try
            {
                return await UserClientKeyHelper.EnsureKeyPairAsync();
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                throw new GuestConnectionException(
                    $"The managed client key could not be created: {ex.Message}");
            }
        }

        if (!File.Exists(identityPath))
            throw new GuestConnectionException($"The identity file '{identityPath}' does not exist.");

        byte[] keyBytes;
        try
        {
            keyBytes = await File.ReadAllBytesAsync(identityPath);
        }
        catch (Exception ex)
        {
            throw new GuestConnectionException(
                $"The identity file '{identityPath}' could not be read: {ex.Message}");
        }

        try
        {
            // Normalize CRLF -> LF before import: a key generated by Windows
            // ssh-keygen (or exported by DevTunnels) carries CRLF, and the same
            // normalization the managed key path applies on write is needed here on
            // read so the import does not trip over the line endings.
            return KeyPair.ImportKeyBytes(OpenSshKeyBytes.NormalizeLineEndingsToLf(keyBytes));
        }
        catch (Exception ex)
        {
            throw new GuestConnectionException(
                $"The identity file '{identityPath}' could not be loaded as an SSH key: {ex.Message}");
        }
    }
}
