using Eryph.GuestServices.Client;
using Microsoft.DevTunnels.Ssh;
using Microsoft.DevTunnels.Ssh.Algorithms;
using Microsoft.DevTunnels.Ssh.Keys;

namespace Eryph.GuestServices.Tool.Transport;

// Builds the library's guest connectors for egs-tool, resolving the SSH key from
// the Windows key stores that stay in the tool: the machine-wide service key for
// the Hyper-V transport, and the per-user managed key (or a BYOK identity file)
// for the eryph channel. The library connectors themselves take an already
// resolved IKeyPair, so this key-acquisition policy lives here, not in the lib.
internal static class ToolGuestConnectors
{
    // Hyper-V socket: the machine-wide service client key created by 'initialize'.
    internal static async Task<IGuestConnector> CreateHyperVAsync(Guid vmId)
    {
        var keyPair = await ClientKeyHelper.GetKeyPairAsync()
            ?? throw new GuestConnectionException(
                "No SSH key found. Have you run the initialize command?");

        return new HyperVGuestConnector(vmId, keyPair);
    }

    // eryph channel: resolve the connection the same way the eryph CLI does, then
    // the operator's managed key (created on demand) or the BYOK identity key.
    internal static async Task<IGuestConnector> CreateEryphAsync(
        string catletId,
        string? clientId,
        string? configurationName,
        string? identityPath,
        Action<string>? writeWarning)
    {
        var connection = EryphConnection.Resolve(clientId, configurationName)
            ?? throw new GuestConnectionException(
                "Could not find an eryph connection. Is eryph configured or eryph-zero running?");

        var keyPair = await ResolveEryphKeyAsync(identityPath);

        return new EryphGuestConnector(connection, catletId, keyPair, writeWarning);
    }

    // The managed key (created on demand under the operator's profile) by default,
    // or the BYOK private key the operator selected with --identity. The BYOK key
    // is loaded here because the in-process session has to sign with it, unlike
    // 'catlet add-ssh-config' which only writes its path into the ssh_config.
    private static async Task<IKeyPair> ResolveEryphKeyAsync(string? identityPath)
    {
        if (string.IsNullOrEmpty(identityPath))
        {
            try
            {
                return await UserClientKeyHelper.EnsureKeyPairAsync();
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                throw new GuestConnectionException(
                    $"The managed client key could not be created: {ex.Message}");
            }
        }

        if (!File.Exists(identityPath))
            throw new GuestConnectionException($"The identity file '{identityPath}' does not exist.");

        byte[] keyBytes;
        try
        {
            keyBytes = await File.ReadAllBytesAsync(identityPath);
        }
        catch (Exception ex)
        {
            throw new GuestConnectionException(
                $"The identity file '{identityPath}' could not be read: {ex.Message}");
        }

        try
        {
            // Normalize CRLF -> LF before import: a key generated by Windows
            // ssh-keygen (or exported by DevTunnels) carries CRLF, and the same
            // normalization the managed key path applies on write is needed here on
            // read so the import does not trip over the line endings.
            return KeyPair.ImportKeyBytes(OpenSshKeyBytes.NormalizeLineEndingsToLf(keyBytes));
        }
        catch (Exception ex)
        {
            throw new GuestConnectionException(
                $"The identity file '{identityPath}' could not be loaded as an SSH key: {ex.Message}");
        }
    }
}
